- name: Install Maven
  ansible.builtin.dnf:
    name: maven
    state: installed

- name: setup application
  ansible.builtin.import_role:
    name: common
    tasks_from: app-setup

- name: Build the application
  ansible.builtin.command:
    cmd: mvn clean package
  args:
    chdir: /app

- name: Move the JAR file
  ansible.builtin.command:
    cmd: mv /app/target/shipping-1.0.jar /app/shipping.jar

- name: start the application
  ansible.builtin.import_role:
    name: common
    tasks_from: systemd-setup

- name: Install MySQL client
  ansible.builtin.dnf:
    name: mysql
    state: installed

- name: Load schema.sql
  ansible.builtin.shell:
    cmd: mysql -h mysql.joindevops.fun -uroot -pRoboShop@1 < /app/db/schema.sql

- name: Load app-user.sql
  ansible.builtin.shell:
    cmd: mysql -h mysql.joindevops.fun -uroot -pRoboShop@1 < /app/db/app-user.sql

- name: Load master-data.sql
  ansible.builtin.shell:
    cmd: mysql -h mysql.joindevops.fun -uroot -pRoboShop@1 < /app/db/master-data.sql

- name: restart the application
  ansible.builtin.import_role:
    name: common
    tasks_from: systemd-restart
