- name: Install nodejs
  ansible.builtin.import_role:
    name: common
    tasks_from: nodejs

- name: setup application
  ansible.builtin.import_role:
    name: common
    tasks_from: app-setup

- name: Install dependencies
  ansible.builtin.command:
    cmd: npm install
  args:
    chdir: /app

- name: Start application
  ansible.builtin.import_roles:
    name: common
    tasks_from: systemd-setup

- name: load schema
  ansible.builtin.import_roles:
    name: common
    tasks_from: mongo-schema

- name: restart application
  ansible.builtin.import_role:
    name: common
    tasks_from: systemd-restart
