- name: configure rabbitmq yum repos
  ansible.builtin.shell: "{{item}}"
  loop:
    - "curl -s https://packagecloud.io/install/repositories/rabbitmq/erlang/script.rpm.sh | bash"
    - "curl -s https://packagecloud.io/install/repositories/rabbitmq/rabbitmq-server/script.rpm.sh | bash"

- name: install rabbitmq
  ansible.builtin.dnf:
    name: rabbitmq-server
    state: installed

- name: start  rabbitmq-server
  ansible.builtin.service:
    name: rabbitmq-server
    state: started
    enabled: yes

- name: create rabbitmq user
  ansible.builtin.shell: rabbitmqctl add_user roboshop roboshop123

- name: setup permissions
  ansible.builtin.shell: rabbitmqctl set_permissions -p / roboshop ".*" ".*" ".*"