- name: Install nodejs
  ansible.builtin.import_role:
    name: common
    tasks_from: nodejs

- name: setup application
  ansible.builtin.import_role:
    name: common
    tasks_from: app-setup

- name: Install application dependencies
  ansible.builtin.command:
    cmd: npm install
  args:
    chdir: /app

- name: Start application
  ansible.builtin.import_role:
    name: common
    tasks_from: systemd-setup

- name: Load Schema
  ansible.builtin.import_role:
    name: common
    tasks_from: mongo-schema


- name: Restart application
  ansible.builtin.import_role:
    name: common
    tasks_from: systemd-restart
