- name: Check if roboshop user exists
  ansible.builtin.command:
    cmd: id roboshop
  register: out
  ignore_errors: true

- name: Create roboshop user if not exists
  ansible.builtin.user:
    name: roboshop
  when: out.rc != 0

- name: Check if /app directory exists
  ansible.builtin.stat:
    path: /app
  register: directory

- name: Create /app directory if not exists
  ansible.builtin.file:
    path: /app
    state: directory
  when: directory.stat.exists == False

- name: "Download the {{component}} artifact"
  ansible.builtin.get_url:
    url: "https://roboshop-builds.s3.amazonaws.com/{{component}}.zip"
    dest: /tmp

- name: Unzip the downloaded application code
  ansible.builtin.unarchive:
    src: /tmp/{{component}}.zip
    dest: /app
    remote_src: yes
